version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 app:app

  filereader:
    build: .
    ports:
      - "7000:7000"
    environment:
      - FLASK_APP=filereader.py
    command: gunicorn --workers 3 --bind 0.0.0.0:7000 filereader:app

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: service_status
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
