version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # 외부에 노출되는 Flask 애플리케이션의 포트
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000

  filereader:
    build: .
    ports:
      - "7000:7000"  # 내부 API 서비스 포트 
    environment:
      - FLASK_APP=filereader.py
    command: flask run --host=127.0.0.1 --port=7000
